### ISSUE TITLE
AttributeError: 'float' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Auxxxxlx** [amal-hasni/spot-language#1]
problem code
```javascript
vectorizer.fit(X_train)
```
<img width="942" alt="截屏2021-04-03 下午7 48 56" src="https://user-images.githubusercontent.com/13865581/113477606-a39e8b00-94b5-11eb-9d12-e22534fd239b.png">

<img width="979" alt="截屏2021-04-03 下午7 51 56" src="https://user-images.githubusercontent.com/13865581/113477674-0d1e9980-94b6-11eb-8028-72747a3544f7.png">

`data.csv` is downloaded through [kaggle](https://www.kaggle.com/alecyrus/creating-labeled-code-snippets-dataset-7a8098/edit)

**Comment by hmiladhia** [comment]
The problem seems to be with the database containing NaNs which are of float type and not str (therefore, they don't have the "lower" method).

Are you sure, you've run all the cells in Kaggle? Specifically, this one which is supposed to remove NaN values ?:
![image](https://user-images.githubusercontent.com/23433079/113485083-27537a00-94ac-11eb-9f0b-33e45c3af2a5.png)
